#Sprint-11
melkoto/java-filmorate pull request #6
Opened 2023-02-05 17:22 UTC by melkoto

2023-02-06 18:59 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-06 18:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/controllers/FilmController.java
> +    public Optional<Film> getFilmById(@PathVariable long id) {
Нет же... из контроллера уже не может "торчать" `Optional` !
На фронт мы уже должны ответить вполне конкретно, или мы нашли сущность и её возвращаем или кидаем исключение говорящее что сущность не найдена.

2023-02-06 18:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/dao/impl/FilmDaoImpl.java
> +            throw new BadRequestException("Возрастной рейтинг с id " + film.getMpa().getId() + " не найден");
Допущена вполне стандартная ошибка... ничего не делающие сервисы!
Если мы посмотрим на сервис увидим только вызов метода из dao.

А тут, делается всё то что должно было бы быть в сервисе!
Вот эта проверка с бросанием BadRequestException это как раз то что должен делать сервис!

В методе `addFilm` уместен только запрос на сохранение insertFilm и запрос на сохранение жанров - insertFilmGenre

2023-02-06 18:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/dao/impl/FilmDaoImpl.java
> +        String sql = "SELECT id FROM films";
Тут тоже происходит нечто ужасное! ))
Воспользуйся SQL и получи все фильмы одним запросом! 
Вместо того чтобы проходиться в цикле и дергать их по одному... это же убивает производительность - никогда так больше не делай!

Но смотри не наступи на еще одни грабли... после того как вытащишь все фильмы, тебе в сервисе нужно будет сходить еще и за жанрами ко всем фильмам! И это тоже важно сделать одним запросом! 
И всю работу проводи в сервисе - комбинируя dao фильмов и жанров!

2023-02-06 18:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/dao/impl/FilmDaoImpl.java
> +            Genre genre = new Genre();
Этот код должен быть только в GenreDaoImpl.
Ты пытаешься всё делать из dao вместо того чтобы всё делать из сервисов, поэтому возникает вот такое дублирование кода!

2023-02-06 18:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/dao/impl/GenreDaoImpl.java
> +            throw new BadRequestException("Жанр с id " + id + " не найден");
Не кидаем таких эксепшенов из dao! Эта проверка должна быть в сервисе!

В последующих dao те же проблемы, там тоже вынести код в сервисы...

2023-02-06 18:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/models/Film.java
> +    private Genre[] genres;
Почему решил работать с массивом, а не с коллекцией?
Например `Set<Genre> genres`

2023-02-06 18:59 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/storages/film/InMemoryFilmStorage.java
> +        return null;
Не поддерживаем более InMemory реализации, и вообще можно удалить их...

2023-02-06 18:59 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    id   LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
А где ты раздобыл `LONG` - тип для чисел в этой БД?

https://h2database.com/html/datatypes.html

BIGINT ?

В postgres, который будет далее, тоже есть bigint
https://www.postgresql.org/docs/current/datatype-numeric.html

2023-02-08 20:22 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-08 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/dao/FilmDao.java
> +    SqlRowSet getFilms();
SqlRowSet не должен "просочиться" на другой "уровень", на уровень сервисов из дао.

2023-02-08 20:22 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/services/film/FilmService.java
> +        Film film = new Film();
У нас есть непонимание как построить Film с его зависимостями от других сущностей...

И у нас есть два примера
Genre[] genres; (Должны быть List<Genre> !!!) - список
Mpa mpa; - одна сущность

Так вот можно было бы и то и то получить отдельно в этом сервисе и потом засетить в сущность, но не нужно же прям всю сущность строить в сервисе!

Но к `Mpa` можно применить и другой подход.
Выстроить запрос на получение фильма через join с mpa.
Таким образом с одного запроса получив Film с его Mpa.

Но с жанрами так не прокатит. Их в любом случае выгоднее получить одним запросом для всех фильмов сразу!

Блин... боюсь тебя запутать, поэтому будет вполне норм если ты просто сходишь и за Genre и за Mpa отдельными запросами из сервиса.

2023-02-10 18:35 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-10 18:35 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/dao/FilmDao.java
> +    Film getFilmById(Long id);
А я тебе присылал какую сигнатуру для этого метода?

`Optional<Film> getFilmById(Long id);`

Ты не готов еще работать с Optional ?

2023-02-10 18:35 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/dao/GenreDao.java
> +    SqlRowSet getUniqueGenresByFilmId(Long filmId);
Тут почему всё еще SqlRowSet ?

Аааа... метод не используется! Удали это пережиток предыдущей реализации...

2023-02-10 18:35 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/dao/impl/FilmDaoImpl.java
> +        Film film = new Film();
У тебя есть метод buildFilm !
Надо было бы им и воспользоваться!

2023-02-10 18:35 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/services/film/FilmService.java
> +        for (Film film : films) {
Вот всё таки не удалось нам обойти эту ошибку.

Вот так в лоб нельзя делать в данном случае!

Давай поясню...
пусть у нас есть 100 фильмов... а у каждого из них есть жанры
для того чтобы собрать всё в одно и отдать при запросе нам нужно:

- достать все фильмы
- и все жанры к ним

Если делать "в лоб" то приходиться к каждому из 100-а фильмов отдельным запросом доставать еще и жанры...
получается ОДИН запрос на получение всех 100 фильмов и еще 100 запросов чтобы к каждому фильму подтянуть жанры....

Это называется проблема `N+1`
Чтобы её избежать мы должны заморочиться и в итоге придти к всего ДВУМ запросам, вместо 101 !

Первый запрос на все фильмы, второй на все жанры для этих фильмов.
И все эти манипуляции следует выполнять в сервисе.

2023-02-11 21:00 UTC, melkoto commented on src/main/java/ru/yandex/practicum/dao/impl/FilmDaoImpl.java
> +        Film film = new Film();
Здесь не смог использовать, потому что другой тип. Что-то общее придумать не смог

2023-02-12 06:40 UTC, FanaticFiz approved these changes

2023-02-12 06:40 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/services/film/FilmService.java
> +        Map<Long, List<Genre>> genresOfFilms = genreService.getGenresOfFilms();
Тебе нужно сделать вот что!
Залогировать обращение к БД и ты увидишь наглядно сколько запросов сыпется. 

Проблема не решилась! Чтобы её разрулить надо сходить за всеми жанрами для всех фильмов одним запросом.
Сигнатура должна быть такой: `genreService.getGenresOfFilms(films);`

А SQL-ем ты выберешь применив `IN ()`

2023-02-27 14:44 UTC, merged